<?xml version="1.0" encoding="utf-8"?><Database Name="MahasiswaDB" Class="MHSDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=HADI-PC;Initial Catalog=MahasiswaDB;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="MahasiswaDBConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Tmahasiswa" Member="Tmahasiswas">
    <Type Name="Tmahasiswa">
      <Column Name="NRP" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Nama" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Fakultas" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Jurusan" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="Tmahasiswa_Tnilai" Member="Tnilais" ThisKey="NRP" OtherKey="NRP" Type="Tnilai" />
    </Type>
  </Table>
  <Table Name="dbo.Tnilai" Member="Tnilais">
    <Type Name="Tnilai">
      <Column Name="KodeMK" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="MataKuliah" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Nilai" Type="System.String" DbType="NVarChar(2) NOT NULL" CanBeNull="false" />
      <Column Name="NRP" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Tmahasiswa_Tnilai" Member="Tmahasiswa" ThisKey="NRP" OtherKey="NRP" Type="Tmahasiswa" IsForeignKey="true" />
    </Type>
  </Table>
</Database>